apiVersion: v1
kind: Service
metadata:
  name: sample-service
  namespace: default
  labels:
    app: sample-service
spec:
  type: NodePort
  selector:
    app: sample
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 8082
      nodePort: 30000
